config/routes.rb
require 'resque/server'

RealLifeSocial::Application.routes.draw do
  mount Resque::Server.new, :at => "/you_dont_know_this_url"

  root :to => 'welcome#index'

  devise_for :users
  resources :users, only: :show, key: :uid do
    member do
      get 'ready'
    end
  end
  match '/user/sign_out' => 'users#destroy', as: :user_sign_out, via: :delete
  match '/users/auth/:provider/callback' => 'users#create', as: :user_callback

end

app/models/checkin_data.rb
class CheckinData
  include Mongoid::Document

  field :place_name, :type => String
  field :place_long, :type => String
  field :place_lat, :type => String
  field :place_link, :type => String
  field :place_category, :type => String

  field :checkin_id, :type => String
  field :page_id, :type => String
  field :timestamp, :type => DateTime
  embedded_in :user_checkin

end

app/models/user.rb
class User
  include Mongoid::Document
  @queue = :real_life_social_user

  devise :omniauthable, :authenticatable

  field :email, :type => String
  field :name, :type => String
  field :photo_url, :type => String
  field :provider, :type => String
  field :uid, :type => Integer
  field :token, :type => String
  field :registered, :type => Boolean, :default => false
  field :last_timestamp, :type => Integer
  field :processing, :type => Boolean, :default => false
  field :friends, :type => Array, :default => []

  has_many :checkins_as_user1, :class_name => 'UserCheckin', :inverse_of => :user1
  has_many :checkins_as_user2, :class_name => 'UserCheckin', :inverse_of => :user2

  def apply_omniauth(auth)
    self.email = auth['extra']['raw_info']['email']
    self.provider = auth['provider']
    self.uid = auth['uid']
    self.token = auth['credentials']['token']
    self.name = auth['info']['name']
    self.photo_url = auth['info']['image']
    self.registered = true
  end

  def can_see?(other_user_uid)
    uid.to_s == other_user_uid.to_s or self.friends.include?(other_user_uid.to_s)
  end

  def picture
    "http://graph.facebook.com/#{uid}/picture"
  end

  def large_picture
    picture + '?type=large'
  end

  def top_friends
    checkins_as_user1.desc(:count).limit(10)
  end

  def worst_friends
    checkins_as_user1.asc(:count).limit(10)
  end

  def most_recent
    checkins_as_user1.desc(:'checkin_data.timestamp').limit(10)
  end

  def last_checkin
    @last_checkin ||= most_recent[0].checkin_data.to_a.max_by(&:timestamp)
  end

  def data_available?
    !!last_timestamp
  end

  def self.perform(user_id)
    begin
      user = User.find(user_id)

      graph = Koala::Facebook::API.new(user.token)

      friends_list = graph.fql_query('SELECT uid2 FROM friend WHERE uid1 = me()')
      user.friends = friends_list.collect{|u| u['uid2']}

      @checkins = graph.fql_query(<<-EOF
        SELECT author_uid, checkin_id, tagged_uids, page_id, timestamp
        FROM checkin
        WHERE
          author_uid = me() OR
          author_uid in (SELECT uid2 FROM friend WHERE uid1 = me())
        LIMIT 10000
      EOF
      )

      if user.last_timestamp
        @checkins.keep_if { |checkin| checkin['timestamp'].to_i > user.last_timestamp }
      end
      last_timestamp = 0

      @checkins.each do |checkin|
        related_users = [checkin['author_uid']] + checkin['tagged_uids']
        next unless related_users.include?(user.uid)

        other_users_ids = related_users - [user.uid]
        other_users = other_users_ids.each do |id|
          id = id.to_i
          other_user = User.where(:uid => id).first

          unless other_user
            user_data = graph.fql_query("SELECT uid, name, pic_square FROM user WHERE uid = #{id}")[0]
            other_user = User.create!(:uid => id, :name => user_data['name'], :photo_url => user_data['pic_square'])
          end

          user_checkin = UserCheckin.where(:user1 => user, :user2 => other_user).first
          unless user_checkin
            user_checkin = UserCheckin.create!(:user1 => user, :user2 => other_user)
          end

          timestamp = checkin['timestamp'].to_i
          if timestamp > last_timestamp
            last_timestamp = timestamp
          end

          place_data = graph.get_object(checkin['page_id'])
          place_data['location'] = place_data['location'] || {}
          checkin_data = CheckinData.new(
            :place_name => place_data['name'],
            :place_long => place_data['location']['longitude'],
            :place_lat => place_data['location']['latitude'],
            :place_link => place_data['link'],
            :place_category => place_data['category'],
            :checkin_id => checkin['checkin_id'],
            :page_id => checkin['page_id'],
            :timestamp => DateTime.parse(Time.at(timestamp).to_s)
          )
          user_checkin.checkin_data.push(checkin_data)
          user_checkin.count = (user_checkin.count || 0) + 1

          user_checkin.save!
        end
      end

      user.processing = false
      user.last_timestamp = last_timestamp
    rescue Koala::Facebook::APIError
      Resque.enqueue(User, user.id)
    ensure
      user.save!
    end
  end
end

app/models/user_checkin.rb
class UserCheckin
  include Mongoid::Document

  field :count, :type => Integer
  field :last_timestamp, :type => DateTime

  belongs_to :user1, :class_name => 'User', :inverse_of => :checkins_as_user1
  belongs_to :user2, :class_name => 'User', :inverse_of => :checkins_as_user2

  embeds_many :checkin_data

  def month_count
    groups = checkin_data.group_by { |d| "#{d.timestamp.year}_#{d.timestamp.month}" }
    current_month = Time.now.month
    current_year = Time.now.year

    ((current_month - 11)..current_month).map do |month|
      year = current_year
      if month <= 0
        month = 12 + month
        year -= 1
      end

      (groups["#{year}_#{month}"] || []).size
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, except: [:create]
  before_filter :get_user, :only => [:show, :ready]

  def get_user
    if params[:id] == 'me'
      @user = current_user
    else
      @user = User.where(:uid => params[:id], :registered => true).first
    end
  end

  def create
    auth = request.env["omniauth.auth"]

    user = User.where(uid: auth['uid']).first

    if user
      flash[:notice] = "Signed in successfully."
    else
      user = User.new
      flash[:notice] = "Account created and signed in successfully."
    end

    user.apply_omniauth(auth)
    user.processing = true
    user.save!
    Resque.enqueue(User, user.id)

    sign_in user
    redirect_to user_url(:me)
  end

  def show
    redirect_to root_url if @user.nil? or !current_user.can_see?(@user.uid)
  end

  def ready
    render(:json => {:ready => @user.data_available?})
  end

  def destroy
    sign_out current_user
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    return unless current_user

    @user = current_user
    @user_checkins = @user.checkins_as_user1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def image_url(source)
    "#{root_url}#{image_path(source)}"
  end

end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def months_labels
    months = %w( Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec )
    current_month = Time.now.month
    ((current_month - 11 - 1)..current_month - 1).map { |m| months[m] }.inspect
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def users_total
    User.count
  end

  def checkins_total
    User.all.inject(0){|sum, u| u.checkins_as_user1.count + sum}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Real Life Social</title>
    <meta property="og:title" content="Real Life Social" />
    <meta property="og:url" content="http://timehome.r12.railsrumble.com" />
    <meta property="og:image" content="<%= image_url('logo.png')%>" />
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="fb-root"></div>
    <div class='navbar navbar-inverse navbar-static-top'>
      <div class='navbar-inner'>
        <div class='container'>
          <a class='brand' href='/'>
            Real Life Social
          </a>
          <div class="pull-right login">
            <% if user_signed_in? %>
              <span>Welcome <%= current_user.name %></span>
              <%= link_to 'my profile', user_url(:me) %>
              <%= link_to 'logout', user_sign_out_url, method: :delete %>
            <% else %>
              <span class='f_logo'></span>
              <%= link_to 'login', '/users/auth/facebook', class: 'button' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <%= yield %>

    <footer class='footer'>
      <div class='container'>
        Real Life Social is a <a href='http://railsrumble.com/entries/164-timehome'>Timehome</a> production.
        Made in 48 hours or less for the <a href='http://railsrumble.com'>Rails Rumble 2012</a>
      </div>
    </footer>
    <%= yield :javascript_bottom %>
    <script src="http://s0.railsrumble.com/banner.js"></script>
  </body>
</html>

app/views/users/show.html.erb
<section class='profile'>
  <div class='container'>
    <div class='picture'>
      <%= image_tag @user.large_picture, width: 200, alt: @user.name %>
    </div>
    <div class='info'>
      <h2><%= @user.name %></h2>
      <% if @user.data_available? %>
        <p>last seen at <%= @user.last_checkin.place_name %></p>
        <div id='last_checkin_place'></div>
      <% end %>
    </div>
  </div>
</section>

<section class='user-statistics'>
  <% if @user.data_available? %>
    <div class='container'>
      <div class='top10 bf'>
        <h4>best friends</h4>
        <ol>
          <% @user.top_friends.each_with_index do |checkin, i| %>
            <li>
              <span class='position'><%= i + 1 %></span>
              <%= image_tag(checkin.user2.picture) %>
              <span class='info'>
                <% if checkin.user2.registered? %>
                  <%= link_to checkin.user2.name, user_url(checkin.user2.uid) %>
                <% else%>
                  <p><%= checkin.user2.name %></p>
                <% end %>
                <p>checkins: <%= checkin.count %></p>
              </span>
            </li>
          <% end %>
        </ol>
      </div>
      <div class='top10 wf'>
        <h4>worst friends</h4>
        <ol>
          <% @user.worst_friends.each_with_index do |checkin, i| %>
            <li>
              <span class='position'><%= i + 1 %></span>
              <%= image_tag(checkin.user2.picture) %>
              <span class='info'>
                <% if checkin.user2.registered? %>
                  <%= link_to checkin.user2.name, user_url(checkin.user2.uid) %>
                <% else%>
                  <p><%= checkin.user2.name %></p>
                <% end %>
                <p>checkins: <%= checkin.count %></p>
              </span>
            </li>
          <% end %>
        </ol>
      </div>
      <div class='top10 recent'>
        <h4>most recent</h4>
        <ol>
          <% @user.most_recent.each_with_index do |checkin, i| %>
            <li>
              <span class='position'><%= i + 1 %></span>
              <%= image_tag(checkin.user2.picture) %>
              <span class='info'>
                <% if checkin.user2.registered? %>
                  <%= link_to checkin.user2.name, user_url(checkin.user2.uid) %>
                <% else%>
                  <p><%= checkin.user2.name %></p>
                <% end %>
                <p>last: <%= checkin.checkin_data.max(:timestamp).strftime('%D - %T') %></p>
              </span>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
    <div id="line-chart" class="container"></div>
  <% else %>

    <div class="container spinner">
      <p>Hang on, we're preparing your data</p>
    </div>

  <% end %>
</section>

<%= content_for :javascript_bottom do %>
  <%= javascript_include_tag "application", 'http://maps.googleapis.com/maps/api/js?key=AIzaSyCcBv1h8modIzituEdiCCrHAXjwmz_GUfU&sensor=true' %>

  <script>
    (function($) {
      var target = $('.container.spinner');
      if (target.length === 0) {
        return;
      }
      var opts = {
        lines: 13, // The number of lines to draw
        length: 24, // The length of each line
        width: 8, // The line thickness
        radius: 19, // The radius of the inner circle
        corners: 1, // Corner roundness (0..1)
        rotate: 21, // The rotation offset
        color: '#000', // #rgb or #rrggbb
        speed: 1.4, // Rounds per second
        trail: 52, // Afterglow percentage
        shadow: false, // Whether to render a shadow
        hwaccel: false, // Whether to use hardware acceleration
        className: 'spinner', // The CSS class to assign to the spinner
        zIndex: 2e9, // The z-index (defaults to 2000000000)
        top: 'auto', // Top position relative to parent in px
        left: 'auto' // Left position relative to parent in px
      };
      new Spinner(opts).spin(target[0]);

      var checkReadyFunc = function() {
        $.getJSON('<%= ready_user_url(@user.uid) %>.json', function(data) {
          if (data.ready) {
            document.location.href = document.location.href.replace(/#.*$/, '');
          } else {
            setTimeout(checkReadyFunc, 1000);
          }
        });
      };

      setTimeout(checkReadyFunc, 0);
    }(jQuery));
  </script>


  <script>
  $(function() {

    var chart = new Highcharts.Chart({
      chart: {
        renderTo: 'line-chart',
        type: 'line',
        marginRight: 130,
        marginBottom: 25
      },
      title: {
        text: 'Check-ins Over Time',
        x: -20
      },
      xAxis: {
        categories: <%= months_labels().html_safe %>
      },
      yAxis: {
        title: {
          text: 'Check-ins'
        },
        plotLines: [{
          value: 0,
          width: 1,
          color: '#808080'
        }]
      },
      tooltip: {
        formatter: function() {
          return '<b>'+ this.series.name +'</b><br/>'+
          this.x +': '+ this.y;
        }
      },
      legend: {
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'top',
        x: -10,
        y: 100,
        borderWidth: 0
      },
      series: [
      <% @user.checkins_as_user1.each_with_index do |checkin, i| %>
        <% if i > 0 %>,<% end %>
        {
          name: '<%= checkin.user2.name %>',
          data: [<%= checkin.month_count.join(',') %>]
        }
      <% end %>
      ]
    });

  });
  </script>

  <% unless @user.last_timestamp.nil? %>
    <script>
      $(function() {
        var position = new google.maps.LatLng(<%= @user.last_checkin.place_lat %>, <%= @user.last_checkin.place_long %>);
        var mapOptions = {
          center: position,
          zoom: 15,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("last_checkin_place"),
            mapOptions);

        var markerOptions = {
          map: map,
          position: position,
          visible: true,
          title: '<%= @user.last_checkin.place_name %>'
        }

        var marker = new google.maps.Marker(markerOptions);
      });
    </script>
  <% end %>

<% end %>

app/views/welcome/index.html.erb
<section class='welcome'>
  <div class='container'>
    <h1>Real Life Social</h1>
  </div>
</section>

<section class='description'>
  <div class='container'>
    <p>It doesn't matter how many friends you have on facebook if you don't actually meet them.</p>
    <p>Get real!</p>
    <p class='impact'>Get Real Life Social!</p>
    <% unless current_user %>
      <a href='/users/auth/facebook'>Login</a>
    <% end %>
  </div>
</section>

<section class='statistics'>
  <div class='container'>
    <p>Users: <%= users_total %></p>
    <p>Processed checkins: <%= checkins_total %></p>
  </div>
</section>